version: '3'

services:
  api:
    container_name: team-titans-sms-app
    restart: always
    build: .
    command: npm start
    ports:
      - '12055:12055'
    links:
      - mongo
    env_file: .env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27020:27020'
